ecomproject/cart/urls.py
from django.urls import path,include
from .  import views
app_name='cart'
urlpatterns = [
    path('',views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>', views.full_remove, name='full_remove'),

]

ecomproject/ecomproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),

]
if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL,
                                document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

ecomproject/search/urls.py
from django.urls import path,include
from .  import views
app_name='search'
urlpatterns = [
    path('',views.Search, name='Search'),

]

ecomproject/shop/urls.py
from django.urls import path,include
from .  import views
app_name='shop'
urlpatterns = [
    path('',views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>', views.proDetail, name='proDetail'),

]

ecomproject/cart/models.py
from django.db import models
from shop.models import Product,Category
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def subtotal(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecomproject/search/models.py
from django.db import models

# Create your models here.

ecomproject/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250, unique=True)
    slug=models.SlugField(max_length=250, unique=True)
    description=models.CharField(max_length=2500,blank=True)
    image=models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name =models.CharField(max_length=250, unique=True)
    slug =models.SlugField(max_length=250, unique=True)
    description=models.CharField(max_length=2500,blank=True)
    image =models.ImageField(upload_to='product', blank=True)
    price =models.DecimalField(max_digits=10, decimal_places=2)
    category =models.ForeignKey(Category, on_delete=models.CASCADE)
    stock =models.IntegerField()
    available =models.BooleanField(default=True)
    created =models.DateTimeField(auto_now_add=True)
    updated =models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:proDetail',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecomproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product,Category
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create( cart_id=_cart_id(request) )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product,cart=cart,quantity=1)
        cart_item.save(),
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_item=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request, product_id):
    cart=Cart.objects.get(cart_id = _cart_id(request))
    product=get_object_or_404(Product,id =product_id)
    cart_item=CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecomproject/search/views.py
from django.shortcuts import render
from shop.models import Product,Category
from django.db.models import Q
# Create your views here.
def Search(request):
    products=None
    query=None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query, 'products':products})

ecomproject/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from shop.models import Product,Category
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.

def allProdCat(request,c_slug=None):
    c_page=None
    products_l=None
    if c_slug !=None:
        c_page =get_object_or_404(Category,slug=c_slug)
        products_l=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_l=Product.objects.all().filter(available=True)
    paginator=Paginator(products_l,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=Paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
            raise  e
    return render(request,'product.html',{'product':product})

ecomproject/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/cust.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Prompt&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
      <link rel="icon" type="image/x-icon" href="{% static 'img/fav.png' %}" >

</head>
<body>
<div >
{% include 'header.html' %}
{% include 'navbar.html' %}

    {% block content %}



    {% endblock %}

</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>


</body>
</html>

ecomproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is the cart page. proceed to review your items and place the order
{% endblock %}

{% block title %}
  Cart- Amaze cart Company PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <h1 class="text-center"> Your cart is Empty</h1><br>
        <p class="text-center"><a href="{% url 'shop:allProdCat' %}">Add items</a> </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center"> Your cart</h1><br>
            <br>
    </div>

    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_cust_table">
                <thead class="my_cust_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
                </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image" style="width:100px; height:150px"></a>
                </td>
                <td class="text-lef">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: ${{cart_item.product.price}}
                    <br>
                    Qty:{{cart_item.quantity}} X  {{cart_item}}
                </td>
                <td>
                     $ {{cart_item.subtotal}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock%}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="cust_a"><i class="fa fa-plus"></i></a>
                    <br> <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fa fa-minus"></i></a>
                    <br> <a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fa fa-trash" ></i></a>
                </td>
                {% else %}
                    <td>
                    <br> <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fa fa-minus"></i></a>
                    <br> <a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fa fa-trash" ></i></a>
                </td>
                    {% endif %}
            </tr>
            {% endfor %}
            </tbody>
            </table>

        </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6">
    <table class="table my_cust_table">
                <thead class="my_cust_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
                </thead>
        <tbody>
        <tr>
            <td>
                Please review your shopping cart items before proceeding with the order payemnt.
            </td>
        </tr>
        <tr>
            <td class="text-left">
                Your total is : <strong>{{total}}</strong>
            </td>
        </tr>
        </tbody>
    </table>
<div class="mx-auto">
    <a href="{% url 'shop:allProdCat'%}" class="btn btn-secondary btn-block">Continue SHopping</a>
</div>
</div>
    </div>

</div>
{% endif %}
{% endblock %}

ecomproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        Welcome to Amaze Cart where you can buys different items...
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}} - Amaze Cart
    {% else %}
           Welcome to Amaze Cart where you can buys different items...
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
    <div class="row my_row_c">
        <div class="mx_auto">
        <p><a href="{% url 'shop:allProdCat' %}">Our Product Collection</a></p>
        </div>
    </div>
</div>
{% endif %}
{% if category %}
<div class="mx_auto">
<img  src="{{category.image.url}}" alt="{{category.name}}"  width="340px" height="420px">
</div>
<br>
<div>
    <h1 class="text-center">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
    <img  src="{% static 'img/banner.png' %}" alt="our products" width="1500px" height="450px">
</div>
<br>
<div>
    <h1 class="text-center">Our Products Collections</h1>
        <p class="text-justify">Today, there are many dummy/filler text generators to choose from, so you don’t necessarily need to use Lorem ipsum. There’s, for example, Corporate ipsum which is based off of business terminologies. Or Cupcake ipsum for those who love baked goods.</p>
</div>
{% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4" >
            <div class="card text-center" style="width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" width="360px" height="420px"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <br>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
{% endfor %}
        </div>
         {% endif %}
    </div>
<br>
</div>
{% endblock %}

ecomproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <br>

<p class="text-center"> &copy; Amaze Cart pvt ltd. All Rights Reserved</p>
</div>

ecomproject/templates/header.html
{% load static %}
<!--<header>-->
<!--    <center>-->
<!--<a href="{% url 'shop:allProdCat' %}"><img src=" {% static 'img/logo.png' %}" alt= "logimage" width="160px" height="170px">-->
<!--</a>-->
<!--    </center>-->
<!--</header>-->

ecomproject/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
<!--    <a class="navbar-brand" href="#">-->
        <a href="{% url 'shop:allProdCat' %}"><img src=" {% static 'img/logo.png' %}" alt= "logimage" 	style="width:75px; height:75px; overflow: hidden; margin: 30px 90px; border-radius: 50%;" ></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
                   {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                    {% endfor %}
              <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
          {% if item_count > 0 %}
        <li class="nav-item">
          <a href="{% url 'cart:cart_detail' %}" class="nav-link"><i class="fa fa-shopping-cart" aria-hidden="true">Your Cart({{item_count}}) </i></a>
        </li>
          {% endif %}

      </ul>
      <form class="d-flex" role="search" action="{% url 'search:Search' %}" method="get">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" ></i>
        </button>
      </form>
    </div>
  </div>
</nav>

ecomproject/templates/product.html
{% extends 'base.html' %}

{% block metadescription %}
        {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
    {% if category %}
        {{product.name}} - Amaze Cart
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p> <a href="{% url 'shop:allProdCat' %}">Home</a> / <a href="{{product.category.get_url}}">{{product.category}}</a></p>
    </div>
</div>
<br>
<div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div>
                    <div style="min-width:18rem">
                        <img class="my_image1" src="{{product.image.url}}" alt="{{product.name}}">
                    </div>
                </div>
            </div>

            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div>
                <h1>${{product.name}}</h1>
                <p>{{product.price}}</p>
                <p>Product Description</p>
                <p class="text-justify">{{product.description}}</p>
                {% if product.stock <= 0 %}
                <p><b>Out of Stock</b></p>
                {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">ADD to Cart</a>
                {% endif %}
                <br><br>

            </div>
         </div>
        </div>
</div>
{% endblock %}

ecomproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Welcome to Amaze Cart where you can buys different items...
{% endblock %}

{% block title %}
  Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center"> You have Serached for :<b>"{{query}}"</b></p>
</div>

<div class="container">
      <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4" >
            <div class="card text-center" style="width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" width="360px" height="420px"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>

{% empty %}
<div class="row mx-auto">
    <p class="text-center my_search_text">0  Result found</p>

</div>
                    {% endfor %}
</div>

    </div>
{% endblock %}